# Generated by Django 5.1.1 on 2024-09-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state_id', models.CharField(max_length=2)),
                ('website', models.URLField()),
                ('building_department_main_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('municipality_main_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('building_department_main_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('chief_building_official_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteXPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state_id', models.CharField(max_length=10)),
                ('website', models.URLField()),
                ('municipality_main_tel_xpath', models.TextField(blank=True, null=True)),
                ('building_department_main_email_xpath', models.TextField(blank=True, null=True)),
                ('building_department_main_phone_xpath', models.TextField(blank=True, null=True)),
                ('chief_building_official_name_xpath', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
