# Generated by Django 5.1.1 on 2024-09-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spidersweb', '0002_websitexpath_created_at_websitexpath_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitexpath',
            name='skip_website',
            field=models.BooleanField(default=False),
        ),
    ]
